### ISSUE TITLE
zpretty via pre-commit hook and umlauts

### ISSUE THREAD

**Issue by 1letter** [collective/zpretty#127]
How can i prevent, that "zpretty" touch my *.pt files? i use the tool via pre-commt hook. German Umlauts are converted to HTML Entities, thats not what i want. I want only the formatting of *zcml anf *xml Files

**Comment by ale-rt** [comment]
See https://pre-commit.com/#filtering-files-with-types

It should be:

```yaml
  - repo: https://github.com/collective/zpretty
    rev: 3.3.0
    hooks:
      - id: zpretty
        files: ".*.(zcml|xml)$"
```
